name: current10
favicon: null
layout_spectrum: 0.4001966961659491
typography_spectrum: 0.7930828821845353
title: Current10-like Test Site for Grid Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74844900-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ffffff'
    - '#e9a246'
    - '#f6f6f6'
    - '#262626'
  brandStrength: 0.9813181227073073
  lightness: 0.6619078377261758
  saturation: 0.09469284699298441
  rhythmicContrast: 0.2865677406080067
purpose: []
