name: current10
favicon: null
layout_spectrum: 0.4001966961659491
typography_spectrum: 0.7930828821845353
title: Current10-like Test Site for Grid Beta
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74844900-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9813181227073073
  lightness: 0.6619078377261758
  saturation: 0.09469284699298441
  rhythmicContrast: 0.2865677406080067
purpose: []
